services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DB_URL: jdbc:postgresql://db:5432/mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    depends_on:
      - db
    ports:
      - "8080:8080"

  #frontend:
  #  build: ./frontend
  #  environment:
  #    API_URL: http://localhost:8080
  #  depends_on:
  #    - backend
  #  ports:
  #    - "3000:3000"

volumes:
  db_data:
